export * from './regions.service';
export * from './districts.service';
export * from './vet-stations.service';
export * from './animal-types.service';
export * from './colors.service';
export * from './urine-colors.service';
export * from './dung-colors.service';
export * from './vaccine-types.service';
export * from './disease-types.service';
